version: '2'

services:
  test-gui:
    image: node:16
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
    volumes:
      - .:/app
      - server_node_modules:/app/node_modules
    working_dir: /app
    entrypoint:
      - bash
      - -c
      - "apt-get update
         && apt-get install -y
            libasound2
            libatk1.0-0
            libatk-bridge2.0-0
            libcups2
            libdrm2
            libgbm-dev
            libnss3
            libxcomposite1
            libxdamage1
            libxkbcommon0
            libxrandr2
         && yarn
         && yarn test:gui"

  server:
    image: nginx:1.21.5-alpine
    volumes:
      - .:/usr/share/nginx/html

volumes:
  server_node_modules:
    driver: local
