services:
  test-gui:
    build:
      context: .
      dockerfile: tests/gui/Dockerfile
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
    volumes:
      - ./tests:/app/tests
      - ./coverage-gui:/app/coverage-gui
    working_dir: /app

  server:
    image: nginx:1.27.5-alpine
    volumes:
      - .:/usr/share/nginx/html
