version: '3'

services:
  test-gui:
    build:
      context: .
      dockerfile: Dockerfile_guitest
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
    volumes:
      - ./tests:/app/tests
    working_dir: /app

  server:
    image: nginx:1.22.1-alpine
    volumes:
      - .:/usr/share/nginx/html
