name: Feature request
description: Request any feature.
title: "[ENH]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: suggestion-feature
    attributes:
      label: Suggestion feature
      placeholder: Tell us what you request!
    validations:
      required: true
  - type: dropdown
    id: gui-package
    attributes:
      label: Is this a feature to be added to the GUI or to the package?
      multiple: true
      options:
        - GUI
        - package
        - other
    validations:
      required: true
