name: Github Pages
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - '.eslintrc.json'
      - '.gitignore'
      - '.prettierrc.json'
      - 'Dockerfile*'
      - 'docker-compose.yml'
      - 'LICENSE'
      - 'package.json'
      - 'README.md'
      - 'package-lock.json'
jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Prepare ONNX
        run: npm run create-onnx -t
      - name: Test lib
        run: npm run test:lib --bail
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test js
        run: npm run test:js --bail
  test-gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test GUI
        run: docker compose run --rm test-gui --bail
  deploy:
    runs-on: ubuntu-latest
    needs: [test-lib, test-gui, test-js]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          exclude_assets: '.github,tests'
