name: Node.js Package
on:
  release:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: npm install
      - name: Prepare ONNX
        run: npm run create-onnx -t
      - name: Test
        run: npm run test:lib -- --bail 1
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build:npm
      - name: Publish
        run: npm publish
