name: Test
on: pull_request
jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Prepare ONNX
        run: npm run create-onnx -t
      - name: Test lib
        run: npm run test:lib --bail
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test js
        run: npm run test:js --bail
  test-gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test GUI
        run: docker compose run --rm test-gui --bail
